// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiStudy.Context;

#nullable disable

namespace WebApiStudy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250707174233_PopulandoProdutos")]
    partial class PopulandoProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiStudy.Domain.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("WebApiStudy.Domain.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Estoque")
                        .HasColumnType("real");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2025, 7, 7, 17, 42, 33, 199, DateTimeKind.Utc).AddTicks(8863),
                            Descricao = "Coca cola 2l",
                            Estoque = 50f,
                            ImagemUrl = "CocaCola.jpeg",
                            Nome = "Coca Cola",
                            Preco = 13m
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = 2,
                            DataCadastro = new DateTime(2025, 7, 7, 17, 42, 33, 199, DateTimeKind.Utc).AddTicks(8869),
                            Descricao = "Hambúrguer, salada, queijo e tomate com molhos especiais",
                            Estoque = 50f,
                            ImagemUrl = "cheeseSalad.jpeg",
                            Nome = "Lanches",
                            Preco = 15m
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = 3,
                            DataCadastro = new DateTime(2025, 7, 7, 17, 42, 33, 199, DateTimeKind.Utc).AddTicks(8871),
                            Descricao = "Um delicioso mousse de maracujá caseiro",
                            Estoque = 20f,
                            ImagemUrl = "mousse.jpeg",
                            Nome = "Mousse de Maracujá",
                            Preco = 8m
                        });
                });

            modelBuilder.Entity("WebApiStudy.Domain.Produto", b =>
                {
                    b.HasOne("WebApiStudy.Domain.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WebApiStudy.Domain.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
